CREATE TABLE EMPLOYEES (
  EMP_ID INT PRIMARY KEY,
  NAME NVARCHAR(100),
  BANK_ACC_NO NVARCHAR(20),
  DEPT_ID INT,
  JOIN_DATE DATE
);

CREATE TABLE DEPARTMENTS (
  DEPT_ID INT PRIMARY KEY,
  DEPT_NAME NVARCHAR(100)
);

CREATE TABLE SALARY_TRANSACTIONS (
  TRANS_ID INT PRIMARY KEY,
  EMP_ID INT,
  AMOUNT DECIMAL(10, 2),
  TRANS_DATE DATE
);

CREATE TABLE AUDIT_LOGS (
  LOG_ID INT PRIMARY KEY IDENTITY(1,1),
  EVENT_TYPE NVARCHAR(100),
  EMP_ID INT,
  DETAILS NVARCHAR(255),
  LOG_DATE DATE
);
